In [1]:
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from transformer import Transformer
from utils import create_dataloader
from training import train, predict, ascending_data

device = "cuda" if torch.cuda.is_available() else "cpu"

/Users/tonimo/Documents/Developing/Repos/Deep-Learning/deep-learning-env/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
n = 5000
vocab_size = 100
sos = vocab_size
eos = vocab_size + 1
maxlen = 10
pad_idx = 0
inputs, outputs = ascending_data(vocab_size, n, maxlen, sos, eos, pad_idx=0)

In [3]:
i = np.random.randint(0, len(inputs))
print(inputs[i])
print(outputs[i])

[100.   7. 101.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
[101.   7. 100.   0.   0.   0.   0.   0.   0.   0.   0.   0.]


In [4]:
dataloader = create_dataloader(inputs, outputs)

In [5]:
model = Transformer(vocab_size + 2, maxlen + 2, pad_idx)
optimizer = optim.Adam(model.parameters(), 0.00001, betas=(0.9, 0.98), eps=1e-10)

model.to(device);

In [6]:
train(model, optimizer, dataloader, epochs=50, verbose=1)

Training Started
Epoch 1 Started


RuntimeError: The size of tensor a (12) must match the size of tensor b (10) at non-singleton dimension 1

In [ ]:
token = 15
source = np.arange(token, token + maxlen)
print(source)
predict(model, source, sos, eos, maxlen)

[15 16 17 18 19 20 21 22 23 24]


array([[100,  21,  20,  19,  18,  17,  16,  15,  14,  13]])

: 