In [1]:
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from transformer import Transformer
from utils import create_dataloader, ascending_data
from training import train, predict, prompt
from preprocess import Tokenizer

device = "cuda" if torch.cuda.is_available() else "cpu"

/Users/tonimo/Documents/Developing/Repos/Deep-Learning/deep-learning-env/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
tokenizer = Tokenizer()
model = Transformer(30000, 15)
# prompt(model, tokenizer, 101, 102, 15, None)
sequences = np.random.randint(0, 30000, (64, 15))
predict(model, sequences, 101, 15, None)

array([[  101, 15792, 15792,  7091, 18354, 18354, 18354, 18354, 18354,
        18354, 18354, 18354, 18354, 18354, 18354],
       [  101, 15792, 15792, 15792, 18354, 18354, 18354, 18354, 18354,
        18354, 18354, 18354, 18354, 18354, 18354],
       [  101, 15792, 15792, 15792, 18354, 18354, 18354, 18354, 18354,
        18354, 18354, 18354, 18354, 18354, 18354],
       [  101, 15792, 15792, 15792, 18354, 18354, 18354, 18354, 18354,
        18354, 18354, 18354, 18354, 18354, 18354],
       [  101, 15792, 15792, 15792, 18354, 18354, 18354, 18354, 18354,
        18354, 18354, 18354, 18354, 18354, 18354],
       [  101, 15792, 15792, 15792, 18354, 18354, 18354, 18354, 18354,
        18354, 18354, 18354, 18354, 18354, 18354],
       [  101, 15792, 15792,  7091, 18354, 18354, 18354, 18354, 18354,
        18354, 18354, 18354, 18354, 18354, 18354],
       [  101, 15792, 15792, 15792, 18354, 18354, 18354, 18354, 18354,
        18354, 18354, 18354, 18354, 18354, 18354],
       [  101, 15792, 15

In [ ]:
n = 5000
vocab_size = 100
sos = vocab_size
eos = vocab_size + 1
maxlen = 10
pad_idx = 0
inputs, outputs = ascending_data(vocab_size, n, maxlen, sos, eos, pad_idx=0)

In [ ]:
i = np.random.randint(0, len(inputs))
print(inputs[i])
print(outputs[i])

[100.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67. 101.]
[101.  67.  66.  65.  64.  63.  62.  61.  60.  59.  58. 100.]


In [ ]:
dataloader = create_dataloader(inputs, outputs)

In [ ]:
model = Transformer(vocab_size + 2, maxlen + 2, pad_idx)
optimizer = optim.Adam(model.parameters(), 0.00001, betas=(0.9, 0.98), eps=1e-10)

model.to(device);

In [ ]:
train(model, optimizer, dataloader, epochs=50, verbose=1)

Training Started
Epoch 1 Started
Epoch 1 Complete | Epoch Average Loss: 4.3581
Epoch 2 Started
Epoch 2 Complete | Epoch Average Loss: 4.0989
Epoch 3 Started
Epoch 3 Complete | Epoch Average Loss: 3.9712
Epoch 4 Started
Epoch 4 Complete | Epoch Average Loss: 3.9066
Epoch 5 Started
Epoch 5 Complete | Epoch Average Loss: 3.7469
Epoch 6 Started
Epoch 6 Complete | Epoch Average Loss: 3.5015
Epoch 7 Started
Epoch 7 Complete | Epoch Average Loss: 3.1836
Epoch 8 Started
Epoch 8 Complete | Epoch Average Loss: 2.9324
Epoch 9 Started
Epoch 9 Complete | Epoch Average Loss: 2.6901
Epoch 10 Started
Epoch 10 Complete | Epoch Average Loss: 2.5272
Epoch 11 Started
Epoch 11 Complete | Epoch Average Loss: 2.3742
Epoch 12 Started
Epoch 12 Complete | Epoch Average Loss: 2.2208
Epoch 13 Started
Epoch 13 Complete | Epoch Average Loss: 2.1111
Epoch 14 Started
Epoch 14 Complete | Epoch Average Loss: 2.0060
Epoch 15 Started
Epoch 15 Complete | Epoch Average Loss: 1.8994
Epoch 16 Started
Epoch 16 Complete | Epoc

KeyboardInterrupt: 

In [ ]:
token = 15
source = np.arange(token, token + maxlen)
print(source)
predict(model, source, sos, eos, maxlen)