In [1]:
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from transformer import Transformer
from utils import create_dataloader
from training import train, predict, ascending_data

device = "cuda" if torch.cuda.is_avalible() else "cpu"

/Users/tonimo/Documents/Developing/Repos/Deep-Learning/deep-learning-env/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
n = 5000
vocab_size = 100 + 2
sos = vocab_size - 2
eos = vocab_size - 1
maxlen = 10
pad_idx = 0
inputs, outputs = ascending_data(vocab_size, n, maxlen, pad_idx)

In [3]:
i = np.random.randint(0, len(inputs))
print(inputs[i])
print(outputs[i])

[80. 81. 82. 83. 84. 85. 86. 87.  0.  0.]
[87. 86. 85. 84. 83. 82. 81. 80.  0.  0.]


In [4]:
dataloader = create_dataloader(inputs, outputs)

In [5]:
model = Transformer(vocab_size, maxlen, pad_idx)
optimizer = optim.Adam(model.parameters(), 0.00001, betas=(0.9, 0.98), eps=1e-10)

model.to(device)

In [6]:
train(model, optimizer, dataloader, epochs=100, verbose=1)

Training Started
Epoch 1 Started
Epoch 1 Complete | Epoch Average Loss: 4.6707
Epoch 2 Started
Epoch 2 Complete | Epoch Average Loss: 4.5909
Epoch 3 Started
Epoch 3 Complete | Epoch Average Loss: 4.3553
Epoch 4 Started
Epoch 4 Complete | Epoch Average Loss: 3.8623
Epoch 5 Started
Epoch 5 Complete | Epoch Average Loss: 3.4302
Epoch 6 Started
Epoch 6 Complete | Epoch Average Loss: 3.0930
Epoch 7 Started
Epoch 7 Complete | Epoch Average Loss: 2.8410
Epoch 8 Started
Epoch 8 Complete | Epoch Average Loss: 2.6787
Epoch 9 Started
Epoch 9 Complete | Epoch Average Loss: 2.5751
Epoch 10 Started
Epoch 10 Complete | Epoch Average Loss: 2.4286
Epoch 11 Started
Epoch 11 Complete | Epoch Average Loss: 2.3175
Epoch 12 Started
Epoch 12 Complete | Epoch Average Loss: 2.1684
Epoch 13 Started
Epoch 13 Complete | Epoch Average Loss: 2.0400
Epoch 14 Started
Epoch 14 Complete | Epoch Average Loss: 1.9143
Epoch 15 Started
Epoch 15 Complete | Epoch Average Loss: 1.8004
Epoch 16 Started
Epoch 16 Complete | Epoc

In [ ]:
token = 15
source = np.arange(token, token + maxlen)
predict(model, source, sos, eos, maxlen)

array([[1000,  831,  831,  829,  828,  828,  826,  824,  824,  824]])